version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "274595021951"       # replace with your account ID
    AWS_REGION: "ap-southeast-1"         # replace with your region
    ECR_REPO: "public/demo-lab14"      # replace with your ECR repo name
    CONTAINER_NAME: "example" # must match container name in task definition
    DOCKER_BUILDKIT: "1" # Enable BuildKit for better performance and multi-platform builds

phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-8)
      - IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - docker buildx create --use --name mybuilder 
  build:
    commands:
      - echo Building Docker image...
      - cd app/
      - ls -al
      - rm -f index-base.js
      - mv -f index-ecs.js index.js
      - mv -f package-ecs.json package.json
      - echo Check docker buildx version and build image for multiple platforms...
      - docker buildx version
      - docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_URI --push .  
  post_build:
    commands:
      # - echo Pushing image to ECR...
      # - docker push $IMAGE_URI
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
  iscard-paths: yes   # Optional: Prevents original local folder structures from being created inside the zip file