AWSTemplateFormatVersion: '2010-09-09'
Description: Demo 13 - Stack Policies (deploy with policy.json to protect WebServer)

Parameters:
  AmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64

Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t4g.micro
      ImageId: !Ref AmiId
      Tags:
        - Key: Name
          Value: demo-13-protected-ec2

  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Name
          Value: demo-13-logs     # this resource is NOT protected by the policy
